# -*- coding: utf-8 -*-
"""KNNModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wp2rqX7BEoMYLZHpdgaVG_IpuYETToH-
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=43
)
model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)


print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)